name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv venv
        uv sync
        uv add pytest-cov
        cd out/python && uv pip install -e . && cd ../..
    
    - name: Set up environment variables
      run: |
        echo "OPEN_TRANSPORT_API_KEY=${{ secrets.OPEN_TRANSPORT_API_KEY }}" > .env
    
    - name: Run tests
      run: |
        uv run pytest test_api.py -v --cov=./ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
